modLoader = "javafml"
loaderVersion = "[32,)"
#issueTrackerURL = ""
license = "Copyright"

[[mods]]
modId = "chunktimestamps"
version = "${version}"
displayName = "Chunk Timestamps"
authors = "Gjum"
description = '''
Chunk Timestamps
'''
#logoFile = ""

[[dependencies.chunktimestamps]]
modId = "forge"
mandatory = true
versionRange = "[32,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.chunktimestamps]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.1,)"
ordering = "NONE"
side = "CLIENT"
